name: d8 (local)
mail: admin@drupsible.org
slogan: 'London Drupal Show and Tell (local)'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
